version: '3.3'

services:
  app:
    build: ./app
    container_name: gitlab_app
    ports:
      - "5001:5000"
    volumes:
      - ./app/:/home/app/
      # ★? - ./migrations:/usr/src/app/migrations
    networks:
      gitlab_net:
        ipv4_address: 172.36.0.2
    restart: always

networks:
  gitlab_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.36.0.0/24