version: '2.3'

services:
  frontend:
    build: .
    env_file:
      - .env
    ports:
      - $FRONTEND_PORT:8080
    volumes:
      - ./:/app
    #command: /bin/sh -c "yarn install; yarn serve --https"
    command: /bin/sh -c "while :; do sleep 1000; done"