version: '3.3'

services:
  app:
    build: ./app
    container_name: vue_practice
    ports:
      - "5003:5000"
    volumes:
      - ./app/:/home/app/
    env_file: 
      - .env
    restart: always
    command: "flask run --host 0.0.0.0 --debugger --reload --port 5000"